# Generated by Django 4.0.3 on 2022-03-14 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('sku', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('brand', models.CharField(max_length=100)),
                ('times_queried', models.IntegerField(default=0)),
            ],
        ),
    ]
